### ISSUE TITLE
Undefined method 'any?' for nil:NilClass

### ISSUE THREAD

**Issue by destefanis** [brigade/scss-lint#619]
When attempting to lint my scss directory, scss-lint is throwing an error. 

```
scss/components/_category_grid.scss 
undefined method `any?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/config.rb:256:in `excluded_file?'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:31:in `block in find'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:31:in `reject'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:31:in `find'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/cli.rb:57:in `scan_for_lints'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/cli.rb:50:in `act_on_options'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/lib/scss_lint/cli.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.42.2/bin/scss-lint:6:in `<top (required)>'
/usr/bin/scss-lint:23:in `load'
/usr/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues

To help fix this issue, please include:
- The above stack trace
- SCSS-Lint version: 0.42.2
- Sass version: 3.4.19
- Ruby version: 2.0.0
```

When I move the scss-lint file to a new directory, it ignores my config. I've checked older issues and my config doesn't have any indentation settings that seemed to produce this error previously.

Any ideas?

**Comment by lencioni** [comment]
@destefanis I noticed you closed this issue. Were you able to resolve it?
