### ISSUE TITLE
RakeTask fails when invoked by guard-rake

### ISSUE THREAD

**Issue by pfac** [brigade/scss-lint#625]
The rake task works perfectly when invoked directly through the command line, but when using `guard-rake` the following output is generated:

```
15:17:11 - INFO - Starting guard-rake default
15:17:11 - INFO - running default
no implicit conversion of Array into String
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:41:in `directory?'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:41:in `block in extract_files_from'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:40:in `each'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:40:in `extract_files_from'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/file_finder.rb:25:in `find'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/cli.rb:57:in `scan_for_lints'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/cli.rb:50:in `act_on_options'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/cli.rb:27:in `run'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/rake_task.rb:74:in `run_cli'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/rake_task.rb:67:in `block in define'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-rake-1.0.0/lib/guard/rake.rb:55:in `run_rake_task'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-rake-1.0.0/lib/guard/rake.rb:24:in `start'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:82:in `block in _supervise'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:79:in `catch'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:79:in `_supervise'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:22:in `block (3 levels) in run'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:119:in `block (2 levels) in _run_group_plugins'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:117:in `each'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:117:in `block in _run_group_plugins'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:116:in `catch'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:116:in `_run_group_plugins'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:21:in `block (2 levels) in run'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:20:in `each'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:20:in `block in run'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack.rb:32:in `unit_of_work'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:18:in `run'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/commander.rb:34:in `start'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in `execute'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
/Users/pfac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues
```

### Additional info: 

* SCSS-Lint version: `0.42.2`
* Sass version: `3.4.19`
* Ruby version: `2.2.3`
* [.scss-lint.yml](https://github.com/subvisual/blue/blob/master/.scss-lint.yml)

## Solution

I've traced the problem to `SCSSLint::RakeTask#files_to_lint`. Apparently when Guard is the one invoking the task it sets `Rake::TaskArguments` in such a way that `task_args.extras` has the value `[[]]`. Flattening the value seems to solve the problem without breaking anything.

Yet, I was unable to replicate the problem in a spec and can't spend more time digging deeper at the moment, therefore I'm only posting this proposal and not a full PR. If nobody manages to deal with this in the meantime I'll try to get back at it, maybe next week.

Cheers

**Comment by sds** [comment]
Thanks for the report, @pfac. 

I believe the issue is that `guard-rake` is invoking the `scss_lint` rake task with a list of files always explicitly passed. So if no files are passed perhaps you're getting an empty array since you invoke the rake task as `scss_lint[]` or similar. 

I don't use guard-rake, but perhaps this is something that can be fixed upstream, or in your configuration that invokes the `scss_lint` rake task in the first place.

**Comment by sds** [comment]
Closing due to lack of response.

**Comment by pfac** [comment]
Damn, forgot to reply to you @sds, sorry about that. :stuck_out_tongue: 

Unless this is a problem in my configuration, IMO this is probably something to be fixed here, as `guard-rake` is working perfectly with every other tool I currently use (at least regarding this). My goal with this issue was merely to have someone with more knowledge of this project take a better look at it.

No need to reopen this issue, if and when I have the time I'll pick it up and try to dig deeper. If I ever find a solution I'll make a PR mentioning this issue.

Thanks :smile:
