### ISSUE TITLE
.scss-lint.yml is ignored in mac osx

### ISSUE THREAD

**Issue by Bitneko** [brigade/scss-lint#626]
scss-lint recognise the .scss-lint.yml in my window system without any problem but ignore it completely on mac osx.

**Comment by trotzig** [comment]
Can you check so that you are running the same version of scss-lint on the two os:es? It would also be good to see the contents of .scss-lint.yml. I'm running scss-lint on my mac without issues.

**Comment by Bitneko** [comment]
The version on the mac is 0.42.2. The one on window is probably older because I have that since last year, but I can only verify it when I get back to work tomorrow as that's my workplace's workstation.

**Comment by trotzig** [comment]
When I run scss-lint with that file, I get an error:

```bash
henrictrotzig@Henrics-MacBook:~/scss-lint-test
⨠ scss-lint -v
scss-lint 0.42.2
henrictrotzig@Henrics-MacBook:~/scss-lint-test
⨠ echo '.foo {
↳ border: 0
↳ }' > test.scss
henrictrotzig@Henrics-MacBook:~/scss-lint-test
⨠ scss-lint test.scss
undefined method `keys' for nil:NilClass
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/lib/scss_lint/config.rb:96:in `merge_wildcard_linter_options'
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/lib/scss_lint/config.rb:72:in `load_options_hash_from_file'
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/lib/scss_lint/config.rb:19:in `load'
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/lib/scss_lint/cli.rb:112:in `setup_configuration'
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/lib/scss_lint/cli.rb:45:in `act_on_options'
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/lib/scss_lint/cli.rb:27:in `run'
/Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_l
int-0.42.2/bin/scss-lint:6:in `<top (required)>'
/Users/henrictrotzig/.rbenv/versions/2.2.3/bin/scss-lint:23:in `load'
/Users/henrictrotzig/.rbenv/versions/2.2.3/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues

To help fix this issue, please include:
- The above stack trace
- SCSS-Lint version: 0.42.2
- Sass version: 3.4.18
- Ruby version: 2.2.3
- Contents of /Users/henrictrotzig/scss-lint-test/.scss-lint.yml
→ exit status: 70
```

The problem is that the linters in the yaml file aren't indented (everything after `linters:` should be indented one step). If I indent those, it works:

```bash
henrictrotzig@Henrics-MacBook:~/scss-lint-test
⨠ scss-lint test.scss
test.scss:1 [W] TrailingWhitespace: Line contains trailing whitespace
test.scss:2 [W] TrailingSemicolon: Declaration should be terminated by a s
emicolon
```

**Comment by Bitneko** [comment]
Thanks, that solve the problem. The indentation somehow disappear when I copied my working file from my workplace's workstation to my home machine.

**Comment by trotzig** [comment]
I'm glad we figured it out. :)
