### ISSUE TITLE
Crashes when used with guard-css_lint

### ISSUE THREAD

**Issue by gshaw** [brigade/scss-lint#644]
Not sure if the bug is with scss_lint or this gem but since I can only reproduce it with guard-css_lint but the crash is in scss_lint.  It happens with 0.44.0 and 0.44.1.  I posted this in chrisrohr/guard-scss_lint#2 as well.

**Steps to Reproduce**

* Create an empty project with the following files as described in [this gist](https://gist.github.com/gshaw/cfd0b0e0b9e87cd8ac2a).
* Move the `test.css` file into a subfolder called `scss/test.scss`
* Bundle install and run `guard`
* Press enter to run the linter.

**Bug:** Crash

```
[1] guard(main)> 
17:52:19 - INFO - Run all
17:52:19 - INFO - Running ScssLint for all .scss files
17:52:19 - ERROR - Guard::ScssLint failed to achieve its <run_all>, exception was:
> [#331308D0CA5F] NameError: undefined local variable or method `options' for #<SCSSLint::Runner:0x007fa9520a4490>
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.1/lib/scss_lint/runner.rb:29:in `find_lints'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.1/lib/scss_lint/runner.rb:19:in `block in run'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.1/lib/scss_lint/runner.rb:18:in `each'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.1/lib/scss_lint/runner.rb:18:in `run'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-scss_lint-0.1.3/lib/guard/scss_lint.rb:58:in `run'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-scss_lint-0.1.3/lib/guard/scss_lint.rb:50:in `run_on_changes'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-scss_lint-0.1.3/lib/guard/scss_lint.rb:46:in `run_all'
> [#331308D0CA5F] /Users/gerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/runner.rb:82:in `block in _supervise'
```

**Exepcted:** Linter to run and warn.  Note that this will happen if they `test.scss` file is in the root and the guard file is updated to watch the root.

I traced the bug down to a file in scss_lint runner.rb.  It appears to be assuming a hash will be passed but in fact what it's getting is a string.  Patching the file fixes the problem.

lib/scss_lint/runner.rb
```ruby
    # @param file [Hash]
    # @option file [String] File object
    # @option path [String] path to File (determines which Linter config to apply)
    def find_lints(file)
      file = { path: file } if file.is_a?(String)
```

Do you think this is a bug in scss_lint or with the guard gem not passing the correct values?

**Comment by gshaw** [comment]
The bug is with how guard-scss_lint is calling the runner.  It should be passing in array of Hashes but instead it's passing an array of paths.  I'll submit a line fix PR fix to that repository.
