### ISSUE TITLE
undefined method 'fetch'

### ISSUE THREAD

**Issue by jesperronn** [brigade/scss-lint#712]
Hi there. 

Can you help me troubleshoot this error. I get this error both if I run from command line (stacktrace below) and if I run from within Atom editor. 

Note that I have generated a wrapper for rvm to run scss-lint

```

$ atom_scss-lint app/assets/stylesheets/main.scss 
undefined method `fetch' for "dummy":String
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/config.rb:173:in `severity_is_valid?'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/config.rb:163:in `block in ensure_severities_are_valid'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/config.rb:162:in `each'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/config.rb:162:in `ensure_severities_are_valid'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/config.rb:76:in `load_options_hash_from_file'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/config.rb:21:in `load'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/cli.rb:135:in `setup_configuration'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/cli.rb:53:in `act_on_options'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/lib/scss_lint/cli.rb:32:in `run'
/Users/jesper/.rvm/gems/ruby-2.3.0/gems/scss_lint-0.44.0/bin/scss-lint:7:in `<top (required)>'
/Users/jesper/.rvm/gems/ruby-2.3.0/bin/scss-lint:23:in `load'
/Users/jesper/.rvm/gems/ruby-2.3.0/bin/scss-lint:23:in `<main>'
/Users/jesper/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jesper/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues

To help fix this issue, please include:
- The above stack trace
- SCSS-Lint version: 0.44.0
- Sass version: 3.4.21
- Ruby version: 2.3.0
- Contents of /Users/jesper/src/project-reporter/.scss-lint.yml
```

**Comment by sds** [comment]
Hey @jesperronn,

This looks like you have an invalid `.scss-lint.yml` configuration file (it has the contents `dummy` instead of the expected format).

**Comment by jesperronn** [comment]
Thanks @sds 

That was exactly the case! Thanks for spotting! This was my contents:

```
# extends default Scss lint configuration found at
# https://github.com/brigade/scss-lint/blob/master/config/default.yml
#
# and https://github.com/brigade/scss-lint#configuration
scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  some_name: dummy

```
