### ISSUE TITLE
Post install of node-sass binding fails

### ISSUE THREAD

**Issue by wheresrhys** [brigade/scss-lint#907]
I get a 404 for 
```
curl https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-6.10/binding.node
```

The version being targeted appears to not exist https://github.com/sass/node-sass-binaries/releases?after=v3.1.1

Have tried on a few machines. Node 6.10.3

Full error below:
```
$ npm i -D scss-lint
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN prefer global pangyp@2.3.3 should be installed with -g

> node-sass@2.1.1 install /Users/rhys.evans/Projects/next/n-ui/node_modules/scss-lint/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-6.10/binding.node

> node-sass@2.1.1 postinstall /Users/rhys.evans/Projects/next/n-ui/node_modules/scss-lint/node_modules/node-sass
> node scripts/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/rhys.evans/Projects/next/n-ui/node_modules/scss-lint/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
Build failed
```

**Comment by trotzig** [comment]
Hi @wheresrhys! It looks like you're trying to install an npm module named `scss-lint`. This project is bundled as a ruby gem, and installed through `gem install scss_lint`.
